### ISSUE TITLE
Add P2SH Outputs

### ISSUE THREAD

**Issue by MatthewLM** [Vesta-wallet/coinslib#16]
The ability to add P2SH outputs will be added to the library whilst maintaining backwards compatibility of the library interface.

The `NetworkType` class already has the `scriptHash` prefix which can be recognised in `addressToOutputScript`. This function should return an output script for P2SH outputs according to the address. Currently this function creates P2PKH scripts in a convoluted fashion. For P2SH outputs, a new function will be created in `p2sh.dart` called `createP2shOutputScript`. It shall take the script hash and create a P2SH output script. This will allow P2SH outputs to be created programmatically from the script hash without being overcomplicated as in `p2pkh.dart`.

This solution is not perfect but keeps the library interface intact and is simple to implement.

**Comment by bananenwilly** [comment]
This sounds like a viable way to me.
Since we probably have to start over at some point, we should now do what gets us there fastest (while reliably working.)

**Comment by MatthewLM** [comment]
Sure thing, I shall get started. I will make a PR when it is ready. I'll name the branch `16-p2sh-outputs` unless there is an alternative preferred naming scheme?

**Comment by bananenwilly** [comment]
sure
