### ISSUE TITLE
P2WPKH transactions not working

### ISSUE THREAD

**Issue by Abhimanyu121** [Vesta-wallet/coinslib#40]
Hello, I have been trying to send P2WPKH transactions using coinslib, following the example given in test case. 
https://github.com/Vesta-wallet/coinslib/blob/0d4ada186ca493f6994dc0553080a2161f10bc46/test/integration/transactions_test.dart#L88

Whenever I broadcast transactions to Mempool.space APIs. I am getting the following error.
```Response (sendrawtransaction RPC error: {"code":-26,"message":"non-mandatory-script-verify-flag (Signature must be zero for failed CHECK(MULTI)SIG operation)"})```

This is the code snippet I am using

```
final keyPair = BitcoinKeys.getECPairFromWif(wif);
final p2wpkh = new P2WPKH(
      data: new PaymentData(pubkey: uint8ListFromList(keyPair.privateKey!)),
       network: testnet);
final dataOutput = p2wpkh.data.output;
final txb = new TransactionBuilder(network: network);
txb.setVersion(1);
   txoToSpend.forEach((element) {
   txb.addInput(element.txid, element.vout ?? 0, null, dataOutput);
});
txb.addOutput(recipient, amount);
txb.addOutput(senderAddress, utxoValueSum - totalAmount);
final keyPair = BitcoinKeys.getECPairFromWif(wif);
for (int i = 0; i < txb.inputs.length; i++) {
   txb.sign(vin: i, keyPair: keyPair, witnessValue: BigInt.from(100));
}
txb.setVersion(1);
final trx = txb.build();
return trx.toHex();
```

Can someone please help out here?

**Comment by Abhimanyu121** [comment]
@MatthewLM hey i tried with a higher number as well, and still not working

**Comment by MatthewLM** [comment]
> @MatthewLM hey i tried with a higher number as well, and still not working

It needs to exactly the output amount from the previous output.

**Comment by Abhimanyu121** [comment]
Sorry for asking a dumb question but can you please help understand this bit, it's really not that well documented.
So let's say I am signing a tx(vin) at index 1, so the witness value has to be the output amount of vin at 1? Or is it a different output?

**Comment by MatthewLM** [comment]
Yes, it's the output amount you are spending. It is item 6 as documented here: https://github.com/bitcoin/bips/blob/master/bip-0143.mediawiki

**Comment by Abhimanyu121** [comment]
Thanks a lot for this, one last quick question, just to see if I got it correctly, only P2WPKH tx outputs need to be signed with witness value right?

**Comment by MatthewLM** [comment]
No problem. P2WSH inputs do as well.

**Comment by Abhimanyu121** [comment]
Got it, thanks a lot, closing the issue.

**Comment by kazbeksultanov** [comment]
@MatthewLM Hi, I just was stuck for a week, with the same error, and was writing to here. But during my writing somehow, my code just worked =)
But while the was error, I researched your code and noticed one place, that for me was like and error.

I am not, good at bitcoin to be honest. But still wanted to clarify for my self.

```
        if (type == SCRIPT_TYPES['P2WPKH']) {
          input.prevOutType = SCRIPT_TYPES['P2WPKH'];
          input.hasWitness = true;
          input.signatures = [null];
          input.pubkeys = [ourPubKey];

          input.signScript = new P2PKH( //<--- Here why you use P2PKH while this place is for P2WPKH type

                  data: new PaymentData(pubkey: ourPubKey),
                  network: this.network)
              .data
              .output;
        } else {
          // DRY CODE
          Uint8List prevOutScript = pubkeyToOutputScript(ourPubKey!);
          input.prevOutType = SCRIPT_TYPES['P2PKH'];
          input.signatures = [null];
          input.pubkeys = [ourPubKey];
          input.signScript = prevOutScript;
        }
```
https://github.com/Vesta-wallet/coinslib/blob/0d4ada186ca493f6994dc0553080a2161f10bc46/lib/src/transaction_builder.dart#L188-L196
